version: 2

jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.1-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-v1-{{ checksum "project.clj" }}-{{ checksum "package-lock.json" }}
            - deps-v1-
      - run: npm install
      - run: |
          bin/kaocha \
            --plugin junit-xml \
            --junit-xml-file test-results/kaocha/$(date +"%s").xml
      - store_test_results:
          path: test-results
      - save_cache:
          key: deps-v1-{{ checksum "project.clj" }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.m2
            - ~/.cljs/.aot_cache
            - ~/node_modules
